version: '3'
services:

    spark:
        image: docker.io/bitnami/spark:3-debian-10
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - '8081:8080'    # SPARK MASTER UI
        volumes:
            - ./mnt/data:/opt/data

    spark-worker-1:
        image: docker.io/bitnami/spark:3-debian-10
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=4G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - "8082:8081"   # SPARK WORKER UI
        volumes:
            - ./mnt/data:/opt/data

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    airflow:
        build: ./docker/airflow
        restart: always
        container_name: airflow
        depends_on:
            - postgres
        volumes:
            - ./mnt/dags:/usr/local/airflow/dags
            - ./mnt/plugins:/usr/local/airflow/plugins
            - ./mnt/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./mnt/data:/opt/data
        ports:
            - "8080:8080"  # AIRFLOW UI
          #  - "4041:4040"   # SPARK DRIVER UI
        healthcheck:
            test: [ "CMD", "nc", "-z", "airflow", "8080" ]
            timeout: 45s
            interval: 10s
            retries: 10        